.gitignore
.npmignore
README.md
index.js
make.js
package.json
src/Converter.js
src/function/FunctionConverter.js
src/function/FunctionJsDocConverter.js
src/function/index.js
src/index.js
test/function/FunctionJsDocConverter.test.js
test/index.html

Implement FunctionJsDocConverter. See #1

Initial implementation of FunctionJsDocConverter

---

src/sheet/SheetConverter.js

Update the Sheet converter to set the type in the manifest to "sheet".

Change sheet convertTo type to sheet

---

src/gdoc.ts
tests/issues/84-gdoc-pageBreak.gdoc
tests/issues/84-gdoc-pageBreak.test.ts

Closes #84.
@jwijay, this is mainly FYI. Please go ahead and merge if you're OK with the fix.

fix(GDoc): Fix error when pageBreak in document

---

.gitignore
src/pandoc.ts
tests/issues/95-extra-bullet.md
tests/issues/95-extra-bullet.test.ts

Adds a test for https://github.com/stencila/encoda/issues/95. Also makes some minor tweaks to improve bidirectional conversion to/from Pandoc based encoders.

Test for extra bullet

---

.appveyor.yml
.vscode/launch.json
src/xlsx.ts
tests/issues/20-empty-cells.test.ts

fix(CSV): Insert null values for empty Datatable cells

---

src/cli.ts

This reverts commit 66ac9765bdf825f49b8be1bc800f63b4bf073127.

Revert "refactor(CLI): Change let to const to clarify usage"

---

README.md
src/__tests__/index.test.ts
src/codecs/dar/index.ts
src/codecs/pandoc/pandoc.test.ts
src/codecs/pandoc/templates/jats-template.xml
src/index.ts
src/util/type.ts

Adds support for the [DAR](https://github.com/substance/dar) format.

Add DAR codec

---

src/codecs/ipynb/index.ts
src/codecs/ipynb/ipynb.test.ts

Fixes to IPYNB

---

src/codecs/dar/index.ts
src/codecs/html/index.ts
src/codecs/md/index.ts
src/codecs/person/person.test.ts
src/util/index.ts

Makes changes related to changes in the `schema` repo. Will only work with the `84-language-bindings` branch of `schema`.

Updates for changes to schema

---

package-lock.json
package.json

Required for https://github.com/stencila/schema/pull/99

Update Thema version

---

src/codecs/md/index.ts
src/codecs/md/md.test.ts

Addresses the whitespace issues outlined in #179

fix(Markdown): Sanitize white spaces in tables

---

src/codecs/html/html.test.ts
src/codecs/html/index.ts

fix(HTML): HTML string escaping

---

src/codecs/pandoc/index.ts
src/codecs/pandoc/pandoc.test.ts
src/codecs/pandoc/types.ts

Pandoc: Fix encoding of Table nodes

---

src/__tests__/issues/190-coerce.test.ts
src/cli.ts
src/util/coerce.test.ts
src/util/coerce.ts
src/util/schemas.ts
src/util/validate.ts

fix(Coerce): Do not use the useDefaults Ajv option

---

package-lock.json
package.json
src/__tests__/issues/81-codeBlocks.test.ts
src/codecs/csv/csv.test.ts
src/codecs/dmagic/demo-magic.test.ts
src/codecs/dmagic/index.ts
src/codecs/gdoc/index.ts
src/codecs/html/html.test.ts
src/codecs/html/index.ts
src/codecs/ipynb/__file_snapshots__/running-code.json
src/codecs/ipynb/__file_snapshots__/sunspots.json
src/codecs/ipynb/__file_snapshots__/well-switching.json
src/codecs/ipynb/index.ts
src/codecs/ipynb/ipynb.test.ts
src/codecs/md/index.ts
src/codecs/md/md.test.ts
src/codecs/pandoc/index.ts
src/codecs/pandoc/pandoc.test.ts
src/codecs/tdp/index.ts
src/codecs/tdp/tdp.test.ts
src/codecs/xlsx/index.ts
src/codecs/xlsx/xlsx.test.ts
src/codecs/xmd/index.ts
src/codecs/xmd/xmd.test.ts
src/index.ts
src/process.ts
src/util/ensureBlockContent.test.ts

Add support for new Code types/refactor of code types.
TDP tests are failing, deferring to @nokome

Support for execution engines in schema

---

.appveyor.yml
install.js
src/codecs/pandoc/binary.ts

Builds on Appveyor have been failing for some time due to this:
https://ci.appveyor.com/project/nokome/convert/builds/27115649#L35
This PR aims to get Appveyor builds back to green

Fix Appveyor builds

---

src/codecs/html/html.test.ts
src/codecs/html/index.ts
src/codecs/ipynb/__file_snapshots__/running-code.json
src/codecs/ipynb/__file_snapshots__/sunspots.json
src/codecs/md/index.ts
src/codecs/md/md.test.ts
src/codecs/md/stringifyHtml.ts

Decode HTML in markdown

---

src/codecs/html/index.ts

Wraps `CodeChunk` nodes in necessary tags to work with the custom component from Designa
⚠️ Depends on https://github.com/stencila/designa/pull/16
Once that PR is merged and deployed on NPM/Unpkg, the [necessary script](https://github.com/stencila/encoda/pull/270/files#diff-c21a3c7e37c50b46ffa1ea7be006181bR545-R548) tag will hydrate and progressively enhance the custom components.
This also means that we can iterate and enhance existing components without having to re-encode/update documents. It is currently constrained to serve latest package below `v1`, so allows us to push breaking changes down the road if needed.

feat(HTML): Wrap CodeChunks in custom Web Component

---

src/__tests__/issues/183-lists-to-md.test.ts
src/codecs/md/index.ts

Closes #183. This is not a high priority but whilst looking for another issue, I stumbled across this one and was able to make a fix for it relatively quickly.

fix(Markdown): Handle non-block content in list items

---

src/codecs/person/__snapshots__/person.test.ts.snap

Fixes failing tests due to url change: https://travis-ci.org/stencila/encoda/jobs/597423444

chore(Person): Update test snapshot

---

package-lock.json
package.json
src/cli.ts
src/codecs/html/html.test.ts
src/codecs/types.ts
src/util/html.test.ts
src/util/html.ts

Corresponding changes to Thema PR https://github.com/stencila/thema/pull/75
Tracking card: https://github.com/orgs/stencila/projects/4#card-33598535
~~⚠️ The above linked Thema PR needs to be merged, and the dependency updated in Encoda before this PR is merged.~~ Done

Update theme resolution logic

---

src/codecs/pandoc/__file_snapshots__/cite-refs.html
src/codecs/pandoc/binary.ts
src/codecs/pandoc/index.ts

Update Pandoc to get the latest goodness.

fix(Pandoc): Update Pandoc to 2.9.2

---

package-lock.json
package.json
src/codecs/png/index.ts
src/codecs/rpng/index.ts

fix(PNG, RPNG): Improve styling and fix display for CodeChunks

---

src/codecs/md/index.ts
src/codecs/xmd/index.ts
src/util/transform.ts

RMD: Fix bibliography extraction to separate file

---

src/codecs/md/__file_snapshots__/mdReferences.md
src/codecs/md/index.ts
src/codecs/md/md.test.ts

fix(MD): Store extracted references to a `bibliography` key

---

src/codecs/jats/__file_snapshots__/plosone-0091296.yaml
src/codecs/jats/__file_snapshots__/plosone-0093988.yaml
src/codecs/jats/__file_snapshots__/plosone-0178565.yaml
src/codecs/jats/index.ts
src/codecs/plos/__file_snapshots__/pbio-3000349.yaml
src/codecs/plos/__file_snapshots__/pcbi-1007273.yaml
src/codecs/plos/__file_snapshots__/pgen-1008133.yaml
src/codecs/plos/__file_snapshots__/pmed-1002858.yaml
src/codecs/plos/__file_snapshots__/pntd-0007469.yaml
src/codecs/plos/__file_snapshots__/pone-0216012.yaml
src/codecs/plos/__file_snapshots__/ppat-1007958.yaml

This is a PR to related to decoding of JATS for article convert tag issue : #653
Require to have types in [https://github.com/stencila/schema/issues/207](https://github.com/stencila/schema/issues/207)

fix(JATS): Decoding for article issue number

---

src/__tests__/issues/671-rmd-square-bracket.ts
src/codecs/xmd/__file_snapshots__/elife-50356.Rmd
src/codecs/xmd/index.ts

fix(R Markdown): escape right square bracket.

---

src/__tests__/issues/717-rmd-windows-line-endings.ts
src/codecs/xmd/index.ts

fix(XMD): Allow for Windows line endings

---

src/__tests__/issues/737-elife-43154.xml
src/__tests__/issues/737-org-authors.ts
src/codecs/csl/index.ts
src/codecs/elife/__file_snapshots__/46793.yaml
src/codecs/jats/__file_snapshots__/elife-30274-v1.yaml
src/codecs/jats/__file_snapshots__/elife-43154-v2.yaml
src/codecs/jats/__file_snapshots__/elife-46472-v3.yaml
src/codecs/jats/__file_snapshots__/elife-46793-v1.yaml
src/codecs/jats/index.ts
src/codecs/pandoc/index.ts
src/codecs/plos/__file_snapshots__/pcbi-1007273.yaml
src/codecs/plos/__file_snapshots__/pmed-1002858.yaml

fix(Organization authors): Distinguish org authors in JATS & BibTeX

---

src/codecs/jats/__file_snapshots__/plosone-0091296.jats.xml
src/codecs/jats/__file_snapshots__/plosone-0091296.yaml
src/codecs/jats/__file_snapshots__/plosone-0093988.jats.xml
src/codecs/jats/__file_snapshots__/plosone-0093988.yaml
src/codecs/jats/index.ts
src/codecs/plos/__file_snapshots__/pcbi-1007273.yaml
src/codecs/plos/__file_snapshots__/pmed-1002858.yaml
src/codecs/plos/__file_snapshots__/pone-0216012.yaml
src/codecs/plos/__file_snapshots__/ppat-1007958.yaml

fix: Fix mixed citation in JATS

---

src/__fixtures__/image/vega.ts
src/codecs/html/index.ts
src/codecs/vega/index.ts
src/codecs/vega/vega.test.ts

Close #841
Supports https://github.com/stencila/designa/pull/181
This PR is mostly there, but I've got some bits in progress around the Vega version detection based on the spec/schema that I'd like to finalize before merging.

Add Vega codec, and support for Vega figure output to HTML Codec

---

src/codecs/jats/__file_snapshots__/fig.jats.xml
src/codecs/jats/__file_snapshots__/fig.yaml
src/codecs/jats/__fixtures__/fig.xml
src/codecs/jats/index.ts
src/codecs/jats/jats.test.ts

Currently the JATS `fig` decoder only allows for a single child element. However, there can be multiple `graphic` objects for example.
This PR seems to handle this in a general way.
I've tested it with examples taken from https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/fig.html
```xml
<?xml version="1.0"?>
<article>
<front>
<article-meta>
<contrib-group />
</article-meta>
</front>
<body>
<p>Example 1</p>
<fig id="f1" orientation="portrait" position="float">
<graphic xlink:href="f1" />
<attrib>Brookhaven National Laboratory</attrib>
</fig>
<p>Example 2</p>
<fig id="f8" orientation="portrait" position="float">
<label>FIG. 8.</label>
<caption>
<p>Time difference between events F and A as a function of the
length of entering plug for bifurcations B to BXXX, where X stands
for 0 or …
```

fix(JATS): Allow for multiple objects in `fig`

---

src/codecs/jats/__file_snapshots__/87253.json
src/codecs/jats/__file_snapshots__/8758d58a-6c3d-1014-87a3-bbc202f7d832.json
src/codecs/jats/__file_snapshots__/ca7917ff-6cb0-1014-9b19-d05ef1e56b05.json
src/codecs/jats/__file_snapshots__/d6f14042-6db3-1014-b228-f9da7cb8e4cc.json
src/codecs/jats/index.ts

[elifesciences/enhanced-preprints-issues#681]

Remove attempt to convert all caps headings to sentence case 

---

src/codecs/jats/__file_snapshots__/06908fc3-73df-1014-bb56-a21daa237ef0.json
src/codecs/jats/__file_snapshots__/48c60452-6c66-1014-adf9-c7b61873ecd3.json
src/codecs/jats/__file_snapshots__/81445f02-6bf5-1014-892a-9f5909cc27c1.json
src/codecs/jats/__file_snapshots__/87253.json
src/codecs/jats/__file_snapshots__/8758d58a-6c3d-1014-87a3-bbc202f7d832.json
src/codecs/jats/__file_snapshots__/c2c3813f-6c98-1014-8ba7-9ee2cd5f4386.json
src/codecs/jats/__file_snapshots__/ca7917ff-6cb0-1014-9b19-d05ef1e56b05.json
src/codecs/jats/__file_snapshots__/d6f14042-6db3-1014-b228-f9da7cb8e4cc.json
src/codecs/jats/__file_snapshots__/e9291f49-6d06-1014-9500-e156797df82e.json
src/codecs/jats/__file_snapshots__/elife-30274-v1.yaml
src/codecs/jats/__file_snapshots__/elife-43154-v2.yaml
src/codecs/jats/__file_snapshots__/elife-46472-v3.yaml
src/codecs/jats/__file_snapshots__/elife-46793-v1.yaml
src/codecs/jats/__file_snapshots__/elife-52882-v2.yaml
src/codecs/jats/__file_snapshots__/f1000-7-1655-v1.yaml
src/codecs/jats/__file_snapshots__/f1000-8-1394-v1.jats.xml
src/codecs/jats/__file_snapshots__/f1000-8-1394-v1.yaml
src/codecs/jats/__file_snapshots__/f1000-8-978-v1.jats.xml
src/codecs/jats/__file_snapshots__/f1000-8-978-v1.yaml
src/codecs/jats/__file_snapshots__/ijm-00202.jats.xml
src/codecs/jats/__file_snapshots__/ijm-00202.yaml
src/codecs/jats/__file_snapshots__/plosone-0091296.yaml
src/codecs/jats/__file_snapshots__/plosone-0093988.yaml
src/codecs/jats/__file_snapshots__/plosone-0178565.jats.xml
src/codecs/jats/__file_snapshots__/plosone-0178565.yaml
src/codecs/jats/index.ts
src/codecs/jats/jats.test.ts

https://github.com/elifesciences/enhanced-preprints-issues/issues/1242

Reference types as string
