stencila/encoda

- src/Converter.js
- src/function/FunctionJsDocConverter.js
- test/function/FunctionJsDocConverter.test.js
Prevents XML parse errors such as when an example usage text is `x < 4`
> Adds character encoding when creating XML

- jest.config.js
- src/index.ts
- tests/fixtures/thing/simple/simple-thing.json
- tests/helpers.ts
- tests/index.test.ts
This changes the API of several of the main functions:
- where appropriate change parameter `filePath` to `content`, which can be a string of raw content or a file path
- change parameter `mediaType` to `format` in places where either can be used and improve how the parameter is handled in `match`
This refactoring is mainly in preparation for adding compilers that act on plain text string, rather than files
- e.g. a compiler that detects a DOI and parses it into a `Article` by fetching meta data
- e.g. a compiler that [parses a string into a `Person`](https://github.com/stencila/schema/blob/fd19b920b48724731d5b1c7a7dd59b952f6d9caa/schema/organization/Person.ts#L15)
- moving the [implementation of the schema `parser` keyword](https://github.com/stencila/schema/blob/master/CONTRIBUTING.md#th …
> refactor: allow for supplying raw content

- .gitignore
- .nvmrc
- Makefile
- package-lock.json
- package.json
- src/cli.ts
- src/helpers/boot.ts
- src/rpng.ts
Closes #45 
Need to do some testing of the binary on other platforms.
There have been ongoing reports of [issues with Puppeteer and PKG](https://github.com/zeit/pkg/issues/204), so would be nice to verify functionalities which depend on Puppeteer (e.g. rPNG generation).
Another aspect is that the binary generation gives the following warning:
``` sh
> Warning Cannot include directory %1 into executable.
The directory must be distributed with executable as %2.
node_modules/puppeteer/.local-chromium
path-to-executable/puppeteer
```
The command `npm run postpkg` copies Puppeteer/Chrome into the required folder, but it defeats the purpose of having a single binary as now we have two binaries we'd need to ship.
In addition, the puppeteer binary will likely have to change depending on the …
> Add commands to generate CLI binary

- src/gdoc.ts
- src/html.ts
- src/md.ts
- src/pandoc.ts
- tests/gdoc.test.ts
- tests/html.test.ts
- tests/md.test.ts
- tests/pandoc.test.ts
This normalises (?, unifies?) the use of `title` and `text` properties for `ImageObject` across different formats. Previously we were using `caption` and `context` and `description` as target properties for `text` which caused inconsistencies when converting between formats.
Now, for example, for the Stencila `ImageObject` node:
```javascript
{
type: 'ImageObject',
contentUrl: 'https://example.org/image.png',
title: 'title',
text: 'alt text'
}
```
You get this HTML:
```html
title="title"
alt="alt text">
```
And this Pandoc AST:
```javascript
{
t: 'Image',
c: [
emptyAttrs,
[str('alt text')],
['http://example.org/image.png', 'title']
]
}
```
And a `gdoc` node that's consistent, but is rather complicated and not worth showing here :)
> Normalize use of text and title for images

- src/html.ts
- src/index.ts
- src/json5.ts
- src/md.ts
- tests/json5.test.ts
- tests/md.test.ts
[JSON5](https://json5.org/) is "JSON for Humans":
> The JSON5 Data Interchange Format (JSON5) is a superset of JSON that aims
> to alleviate some of the limitations of JSON by expanding its syntax to
> include some productions from ECMAScript 5.1.
This compiler is primarily targeted at developers. Given that it is more forgiving and it has less typing overhead, JSON5 can be a little more convenient than JSON for quickly testing unparsing of Stencila nodes e.g
```bash
stencila convert "{type:'ImageObject', contentUrl: 'https://example.org', text: 'alt', title: 'title'}" --from json5 --to html
```
Versus using JSON:
```bash
stencila convert '{"type":"ImageObject", "contentUrl": "https://example.org", "text": "alt", "title": "title"}' --from json --to html
```
I found myself getting …
> Add JSON5 compiler

- src/cli.ts
- src/index.ts
- src/pdf.ts
- src/puppeteer.ts
- tests/pdf.test.ts
- tests/puppeteer.test.ts
This adds a PDF unparser (but not a parser). It partly addresses https://github.com/stencila/convert/issues/53 but does not use Paged.js (that will be dealt with as part of https://github.com/stencila/convert/issues/62).
This also implements an approach to make use of Puppeteer more efficient as described in https://github.com/stencila/convert/issues/61. If the solution here looks alright, we can apply it to that issue next.
> Add PDF encoder

- README.md
- package-lock.json
- package.json
- src/cli.ts
With the move to having `stencila` as the main CLI, I propose that the CLIs for `encoda`, `dockta`, `nixta` etc follow this pattern of exposing a very simple, low level CLI that is essentially another way of making a function call and intended primary for developers.
These individual CLIs could be chained together following the Unix pattern of composable tools e.g.
```bash
encoda decode my.rmd | dockta build
```
ie. Encoda decodes the Rmd to JSON which is piped into Dockta which builds a Docker image for it. 
The main `stencila` CLI tool would provide an easier way to do this that integrates the package's API's rather than piping, and hides some of the implementation details e.g 
```
stencila build my.rmd --using docker
```
> Simplify the command line interface

- package-lock.json
- package.json
- src/devserve.ts
- src/gdoc.ts
- src/pandoc.ts
- src/tdp.ts
^ As per title. The other uses of console.log / console.error that haven't been replaced are because they were used to send to STDOUT used in scripts that would only be called from the command line.
> feat: Added logging via Stencila Logga

- src/demo-magic.ts
- src/index.ts
- src/templates/demo-magic.sh
- tests/demo-magic.test.ts
Codec for [Demo Magic](https://github.com/paxtonhare/demo-magic) script.
> `demo-magic.sh` is a handy shell script that enables you to script
> repeatable demos in a bash environment so you don't have to type as
> you present. Rather than trying to type commands when presenting you
> simply script them and let `demo-magic.sh` run them for you.
This codec encodes a Stencila `Node` (usually an `Article` authored using
Markdown) as a Bash script that uses the `demo-magic.sh` functions to
provide an interactive demo with simulated typing and other features.
It's very useful for recording screencasts for command line applications.
It supports `Heading`, `Paragraph` and `CodeBlock` nodes with `bash` or
`sh` as the `language`.
You can run the generated script using options. Use `-h` for help. …
> Add codec to create Demo Magic scripts.

- jest.config.js
- src/cli.ts
- src/rpng.ts
- tests/pdf.test.ts
- tests/rpng.test.ts
- tests/teardown.ts
This addresses #61. It takes the approach suggested there, as already implemented for the `pdf` codec. 
I did some ad hoc tests for speed and there was a slight increase in speed. However these tests were not very useful as they are dominated by waiting for network requests (JS and CSS).
> Improve speed of rPNG generation

- package-lock.json
- src/csv.ts
- src/demo-magic.ts
- src/docx.ts
- src/gdoc.ts
- src/html.ts
- src/index.ts
- src/jats.ts
- src/json.ts
- src/json5.ts
- src/latex.ts
- src/lib.d.ts
- src/md.ts
- src/ods.ts
- src/odt.ts
- src/pandoc.ts
- src/pdf.ts
- src/rpng.ts
- src/tdp.ts
- src/xlsx.ts
- src/yaml.ts
- tests/csv.test.ts
- tests/demo-magic.test.ts
- tests/index.test.ts
- tests/pandoc.test.ts
- tests/pdf.test.ts
This PR changes and standardizes type signatures for `encode` functions within each codec.
It also adds some type safety to make sure that the methods are have the correct signature.
The immediate need for these changes was to allow for passing a `theme` argument for setting.
> Add ability to pass options

- src/index.ts
- src/vfile.ts
- tests/vfile.test.ts
I added an `isOuput` flag, which means `isPath` will be more lenient, since it's unlikely that we'd be passing content as the output argument on the command line (as per example in https://github.com/stencila/encoda/issues/90#issuecomment-499746559)
> fix: Be more lenient with detecting output paths. Ref #90

- src/cli.ts
- src/html.ts
- src/index.ts
- src/pdf.ts
- src/rpng.ts
- src/util/bundle.ts
Also moves `isStandalone` and `theme` options to top level encoding options and refactors passing of options.
Closes #118 and #119.
> fix(HTML, RPNG, PDF): Adds `isBundle` encoding option

- src/__tests__/index.test.ts
- src/codecs/__mocks__/ssf.ts
- src/codecs/dmagic/index.ts
- src/codecs/ipynb/index.ts
- src/codecs/pandoc/index.ts
- src/codecs/tdp/index.ts
- src/codecs/xmd/index.ts
- src/index.ts
- src/process.ts
Uses module loading short-circuiting logic and dynamic imports to improve startup times by ~300%
```
real    0m15.570s
user    0m15.370s
sys     0m2.827s
real    0m5.228s
user    0m4.381s
sys     0m1.513s
real    0m7.641s
user    0m5.987s
sys     0m2.134s
--from json '{"key": "value"}' --to json -
real    0m5.209s
user    0m4.388s
sys     0m1.464s
package.json --to json -
real    0m5.918s
user    0m4.879s
sys     0m1.756s
src/codecs/xlsx/__fixtures__/simple-table.xlsx --to csv -
real    0m8.238s
user    0m7.573s
sys     0m1.766s
package.json --to json -
real    0m13.053s
user    0m12.954s
sys     0m2.448s
```
> perf(CLI): Improve startup time by using dynamic module loading

- src/codecs/html/__snapshots__/html.test.ts.snap
- src/codecs/html/html.test.ts
- src/codecs/html/index.ts
- src/codecs/rpng/index.ts
When a Stencila Node does not have an equivalent representation in Pandoc, we render it as rPNGs.
These rPNGs are generated from HTML fragments. Previously these fragments did not contain HTML head style tags, and so were not styled using Thema styles.
We now wrap them in a full HTML document before taking a screenshot of the relevant element.
> fix(Pandoc): Add CSS styles to unsupported nodes rendered as rPNGs

- package-lock.json
- package.json
- src/codecs/ipynb/index.ts
- src/codecs/ipynb/ipynb.test.ts
- src/codecs/ipynb/nbformat-v3.d.ts
- src/codecs/ipynb/nbformat-v3.schema.json
- src/codecs/ipynb/nbformat-v4.d.ts
- src/codecs/ipynb/nbformat-v4.schema.json
- src/codecs/ipynb/nbformat.js
This refactors the  `ipynb` codec to use Jupyter type definitions generated directly from JSON Schema, rather than those in `@jupyter/coreutils` (which, at present, deviate from the JSON Schema). It replaces #132. Incorporating the JSON Schema for Jupyter will also allow runtime validation of notebooks during I/O.
> refactor(IPYNB): Use types generated from JSON Schema

- src/codecs/person/person.test.ts
- src/util/__tests__/util.test.ts
- src/util/index.ts
To improve startup times, makes the `validate`, `coerce`, and related utility functions `async` so that schemas do not need to be loaded synchronously.
Time reduced from `4.6s` to `3.0s` (65%)  for:
```bash
bash -c "time for i in {1..10}; do node dist/cli convert '{}' --from json - --to json; done"
```
Closes #60.
> Improve startup time

- package.json
Follow up to https://github.com/stencila/encoda/commit/945b921392d78408d05a90573739eaf27b0859e4
Previously converting to docx straight from source would work:
``` sh
npx ts-node --files src/cli.ts convert --from html "<p>test</p>"  --to DOCX test.docx
```
but from the compiled code would fail:
``` sh
node dist/cli.js convert --from html "<p>test</p>"  --to DOCX test.docx
```
> Fix Pandoc DOCX template path

- .eslintrc
- package-lock.json
- package.json
- src/__tests__/matchers.ts
- src/codecs/html/__snapshots__/html.test.ts.snap
- src/codecs/html/html.test.ts
- src/codecs/html/index.ts
- src/codecs/ipynb/ipynb.test.ts
- src/util/index.ts
- src/util/transform.ts
- tsconfig.json
- tsconfig.prod.json
Closes #216 and implements transforming more data surrounding references and citations (this includes `Person`, `Organization`, `CreativeWork`, and a few other nodes)
@jwijay Please note that some of the HTML structure you were working with in Thema might not line up 100% with the results of Encoda, so it's something we should review together. I tried to follow the outline detailed in [your PR](https://github.com/stencila/encoda/pull/200), while keeping the output as lean and semantic as possible. However I think there were differences when compared to the test HTML found in the [Thema PR](https://github.com/stencila/thema/pull/10).
This PR:
- Adds support for Cite, CiteGroup, Figure, Collection nodes
- Handles more props on Article/Person/Org/Ref/CreativeWork nodes (both Stencila Schema …
> Add more node types & extract more data from HTML nodes

- encoda
- src/index.ts
- src/util/zip.ts
The full paths were getting pulled into the Zip file when it was created. This strips out the parent dir so only relative paths are in the zip.
Before:
```bash
$ unzip -l /Users/ben/Downloads/example.zip 
Archive:  /Users/ben/Downloads/example.zip
Length      Date    Time    Name
---------  ---------- -----   ----
0  09-17-2019 18:57   /Users/
0  09-17-2019 18:57   /Users/ben/
0  09-17-2019 18:57   /Users/ben/stencila_checkouts/
0  09-17-2019 18:57   /Users/ben/stencila_checkouts/conversions/
0  09-17-2019 18:57   /Users/ben/stencila_checkouts/conversions/b/
0  09-17-2019 18:57   /Users/ben/stencila_checkouts/conversions/b/C/
0  09-17-2019 18:57   /Users/ben/stencila_checkouts/conversions/b/C/bC3RYXonEUv/
4590  09-17-2019 18:57 …
```
> fix: Using relative paths in zip media creation

- src/codecs/html/html.test.ts
- src/codecs/html/index.ts
- src/codecs/rnb/index.ts
- src/codecs/rpng/__fixtures__/test.html
- src/codecs/rpng/index.ts
- src/codecs/rpng/rpng.css
Connects to https://github.com/stencila/designa/pull/17
Once the above PR is merged, we can add `@stencila/components` as a dependency and use the component exposed slot names in here for more resilient HTML generation.
- Wrap CodeOutput in <output> tags 
- Encode CodeExpressions as valid inline HTML elements
> Wrap CodeOutput in <output> tags, Encode CodeExpressions inline HTML elements

- src/codecs/rpng/__fixtures__/test.html
- src/codecs/rpng/index.ts
- src/codecs/rpng/rpng.css
Updating rPNG styles to look closer to CodeChunks and CodeExpressions in Thema previews, and using SVG code icon from feather icon set.
> fix(RPNG Style): Update rPNG styling

- src/util/coerce.test.ts
- src/util/coerce.ts
In the JSON Schema we allow for property names to have aliases. However, it is laborious  to cover all the possible aliases that arise from using alternative conventions for word separation e.g camel case, snake case, kebab case, spaces. This allows for those alternative conventions.
The primary reason for this feature is to give users more flexibility when adding meta-data to documents. e.g. in YAML frontmatter in R Markdown. The need for flexibility was highlighted when creating examples for https://hub.stenci.la/open/
> feat(Coerce): Allow for variants of property names and aliases

- src/codecs/html/html.test.ts
- src/codecs/html/index.ts
Takes a similar approach to that used for `@stencila/components`: uses major version for links to style sheets. This allows for non-breaking Thema fixes and features to be available, without a release of Encoda.
> fix(HTML): Use a major version of Thema styles

- .vscode/settings.json
- README.md
- install.js
- package-lock.json
- package.json
- src/encoda.ts
- src/index.ts
- src/lib.d.ts
This implements the Executa executor API interface by extending `Listener`.
To test, do an `npm install` here (which will register Encoda on the machine), then in Executa do:
```bash
npm run cli -- serve --http --debug
```
Then hit the decode end point (here using `httpie`):
```bash
http POST :8000/decode content='# H1' format=md
```
There are a number of `TODO`s to address. Ping @alex-ketch
> Expose as a Executa executor

- package-lock.json
- package.json
- renovate.json
As well as changing the Renovate schedule, this change should also fix a semantic-release where only the Github pages plugin was configured for release (so that although version tags were being added, there was no NPM publish).
> ci(*): Reconfigure Renovate and semantic-release

- src/codecs/docx/index.ts
- src/codecs/pandoc/__file_snapshots__/cite-bib-file.json
- src/codecs/pandoc/__file_snapshots__/cite-refs.html
- src/codecs/pandoc/__file_snapshots__/cite.json
- src/codecs/pandoc/__fixtures__/Makefile
- src/codecs/pandoc/__fixtures__/README.md
- src/codecs/pandoc/__fixtures__/cite-bib-file.pandoc.json
- src/codecs/pandoc/__fixtures__/cite-refs.md
- src/codecs/pandoc/__fixtures__/cite-refs.pandoc.json
- src/codecs/pandoc/__fixtures__/cite.pandoc.json
- src/codecs/pandoc/__fixtures__/pandoc-json.sh
- src/codecs/pandoc/binary.ts
- src/codecs/pandoc/index.ts
- src/codecs/pandoc/pandoc.test.ts
- src/codecs/pandoc/types.ts
- Updates `pandoc` to 2.9.1
- Ensures that the `pandoc-citeproc` binary used is the one distributed with `pandoc`
> Pandoc update

- src/codecs/md/index.ts
- src/codecs/md/md.test.ts
- src/codecs/rnb/__file_snapshots__/kitchensink.json
- src/codecs/xmd/__file_snapshots__/basic.json
- src/codecs/xmd/__file_snapshots__/kitchensink.json
As discussed over video, this removes the `coerce` call on the decoded MD schema, closes #307 
Down the road we might look into reinstating coercion in a single top-level place in the `index.ts` file.
> fix(MD): Don't coerce decoded MD AST, avoiding false null values

- src/codecs/elife/__file_snapshots__/45123.yaml
- src/codecs/elife/__file_snapshots__/46793.yaml
- src/codecs/jats/__file_snapshots__/elife-30274-v1.jats.xml
- src/codecs/jats/__file_snapshots__/elife-30274-v1.yaml
- src/codecs/jats/__file_snapshots__/elife-46472-v3.yaml
- src/codecs/jats/__file_snapshots__/elife-46793-v1.yaml
- src/codecs/jats/__file_snapshots__/f1000-7-1655-v1.yaml
- src/codecs/jats/__file_snapshots__/f1000-8-1394-v1.yaml
- src/codecs/jats/__file_snapshots__/f1000-8-978-v1.yaml
- src/codecs/jats/__file_snapshots__/plosone-0091296.yaml
- src/codecs/jats/__file_snapshots__/plosone-0093988.yaml
- src/codecs/jats/__file_snapshots__/plosone-0178565.yaml
- src/codecs/jats/index.ts
- src/codecs/plos/__file_snapshots__/pbio-3000349.yaml
- src/codecs/plos/__file_snapshots__/pcbi-1007273.yaml
- src/codecs/plos/__file_snapshots__/pgen-1008133.yaml
- src/codecs/plos/__file_snapshots__/pmed-1002858.yaml
- src/codecs/plos/__file_snapshots__/pntd-0007469.yaml
- src/codecs/plos/__file_snapshots__/pone-0216012.yaml
- src/codecs/plos/__file_snapshots__/ppat-1007958.yaml
Addresses most of #395. The remaining unaddressed items are, IMO, lower priority and this would be useful merged as is.
See the test snapshot diffs to gauge the additional article meta-data being 'decoded' to in-memory data e.g https://github.com/stencila/encoda/pull/396/files#diff-f1d2c7910e700f5b4ed2c16abfcc03fc
See note regarding potential improvements to capturing funding information when the `Grant` type is added to the schema:
https://github.com/stencila/encoda/blob/684d234110b15a78738fa73a5d3330dfb2bf0c9a/src/codecs/jats/index.ts#L474-L479
> feat(JATS): Improve decoding of article front matter

- src/cli.ts
- src/codecs/html/index.ts
- src/codecs/types.ts
- src/util/html.test.ts
- src/util/html.ts
Closes #397
I tried to keep changes as concise and isolated to the `util/html.ts` file as possible in order to avoid merge conflicts.
This change starts representing `themeAssets` as a list of `styles` and `scripts` under the hood, leaving room for passing multiple values for styes and scripts as [outlined in this comment](https://github.com/stencila/encoda/issues/397#issuecomment-579017540) if we ever allow doing so.
Once the large refactoring PRs are in, some cleanup should be done in a followup PR to make the `theme` argument optional.
> feat(Theme): Add ability to pass URLs as theme argument

- src/codecs/jats/__file_snapshots__/elife-30274-v1.jats.xml
- src/codecs/jats/__file_snapshots__/elife-30274-v1.yaml
- src/codecs/jats/index.ts
- src/codecs/jats/jats.test.ts
- src/util/xml.test.ts
- src/util/xml.ts
Closes #550 
Currently this only captures the `<collab>` contributors as an `Organization` node, with the `emails` as `ContactPoints`.
Note that only a single `ContactPoint` node is created for the org containing all the emails, as opposed to one contact point per email. Can go either way on this, but the root of the issue is that we don't really have an idea whether the email addresses belong to the same entity or not.
I tried capturing the members by setting their affiliation to the "collab Org", but wasn't quite sure how to best represent this in the generated HTML and across codecs. Nesting a list of `Person`s inside the `Organization` element doesn't fit with the Schema, right now it's the same as previous behaviour where they're just listed after the Org, but I'm not sure how we'd …
> feat(JATS): Decode <collab> Article authors as an Org

- src/codecs/md/index.ts
- src/codecs/md/md.test.ts
- src/codecs/md/plugins/cite.ts
close #543
The underlying assumption here is that a citation reference is an alphanumeric, with optional hyphen or underscored, string, being matched by the following RegEx `/@([\w|-]+)/`. This means that the following citations are matched:
- `@simple`
- `@alpha1234num`
- `@like-this`
- "some text (*`@with-a-ref`*) like this" [the part in italics]
> feat(MD): Decode Pandoc style text citations

- src/codecs/jats/index.ts
- src/codecs/md/index.ts
- src/util/references.ts
This change introduces a `context` argument for node decode functions in the Markdown codec.
The `context` object is currently populated with the JSON representation of the front matter YAML, which is then used to look up citation reference `content`.
> feat(MD): Decode citation node content from MD frontmatter

- src/codecs/xmd/__file_snapshots__/basic.json
- src/codecs/xmd/__fixtures__/basic.Rmd
- src/codecs/xmd/index.ts
- src/codecs/xmd/xmd.test.ts
Close #591
Note that the references elements are not removed, so there is potential to end up with duplicate reference nodes. This was done to ensure that any references from other (non code-figures) are still able to be resolved.
> Decode Bookdown style figure references to Block Extensions

- src/codecs/bib/__file_snapshots__/article.bib
- src/codecs/bib/__file_snapshots__/small.yaml
- src/codecs/bib/__fixtures__/article.yaml
- src/codecs/csl/__file_snapshots__/10.5334-jors-182.yaml
- src/codecs/csl/__file_snapshots__/article.csl.json
- src/codecs/csl/index.ts
- src/codecs/doi/__file_snapshots__/10.5334-jors-182.yaml
- src/codecs/md/__file_snapshots__/mdReferences.md
- src/codecs/md/__file_snapshots__/mdReferences.references.bib
- src/codecs/md/__fixtures__/mdReferences.references.bib
- src/codecs/md/index.ts
- src/codecs/md/md.test.ts
- src/index.ts
Close #589
This PR implements a feature to extract references into a `<filename>.references.bib` file next to the Markdown file.
This is only done when the article contains more than 5 references.
Converting back from MD attempts to read in this references file again.
> feat(MD): Encode references in a separate file

- src/codecs/html/__file_snapshots__/elife-50356.html
- src/codecs/html/__file_snapshots__/jupyter-notebook-simple.html
- src/codecs/html/__file_snapshots__/kitchen-sink-article.html
- src/codecs/html/__file_snapshots__/math-article.html
- src/codecs/html/__file_snapshots__/plosone-0229075.html
- src/codecs/html/__file_snapshots__/python-code-chunk.html
- src/codecs/html/__file_snapshots__/r-code-chunk-image-output.html
- src/codecs/html/__file_snapshots__/r-code-expression.html
- src/codecs/html/__file_snapshots__/r-notebook-simple.html
- src/codecs/html/index.ts
Ensure that the ES5 script tag of Stencila Components is not loaded for modern browsers.
> fix(HTML): Fix encoding of missing nomodule attribute

- package-lock.json
- src/codecs/jats/__file_snapshots__/elife-30274-v1.yaml
- src/codecs/jats/__file_snapshots__/elife-46472-v3.yaml
- src/codecs/jats/__file_snapshots__/f1000-7-1655-v1.yaml
- src/codecs/jats/__file_snapshots__/f1000-8-1394-v1.yaml
- src/codecs/jats/__file_snapshots__/ijm-00202.yaml
- src/codecs/jats/__file_snapshots__/plosone-0091296.yaml
- src/codecs/jats/__file_snapshots__/plosone-0178565.yaml
- src/codecs/jats/index.ts
- src/codecs/plos/__file_snapshots__/pmed-1002858.yaml
- src/codecs/plos/__file_snapshots__/pntd-0007469.yaml
- src/codecs/plos/__file_snapshots__/ppat-1007958.yaml
This is a copy of #667 created as a branch in this repo so we can all better collaborate on it.
> fix(JATS): Decoding tag table-wrap-foot for table

- src/__tests__/issues/749-plotly-html-tags.ts
- src/codecs/html/index.ts
> fix(HTML): Use innerHTML to avoid escaping in JSON

- src/__tests__/issues/747-md-inline-html.ts
- src/__tests__/matchers.ts
- src/codecs/ipynb/__file_snapshots__/meta-analysis.json
- src/codecs/ipynb/__file_snapshots__/running-code.json
- src/codecs/md/stringifyHtml.ts
This is a PR to fix #747. @alex-ketch I have set up some tests that narrow down the issue. I am pretty sure it has something to do with the [`stringifyHtml`](https://github.com/stencila/encoda/blob/47f39014a26afaf9a2e8145806c0f90565dd5d79/src/codecs/md/stringifyHtml.ts#L89) function (or related functions). Could you take this over please.
> fix(Markdown): Handle embedded inline HTML properly

- README.md
- src/codecs/png/index.ts
- src/codecs/rpng/index.ts
This PR relates to https://github.com/stencila/thema/pull/294.
Screenshot dimensions are now determined by the node size, rather than the browser viewport.
> Fix rpng generation

- src/__fixtures__/article/journal/elife/30274.json
- src/__fixtures__/article/journal/elife/50356.json
- src/codecs/crossref/__file_snapshots__/article-elife-50356.xml
- src/codecs/docx/docx.test.ts
- src/codecs/elife/__file_snapshots__/45123.yaml
- src/codecs/elife/__file_snapshots__/46793.yaml
- src/codecs/html/__file_snapshots__/elife-30274.html
- src/codecs/html/__file_snapshots__/elife-50356.html
- src/codecs/html/index.ts
- src/codecs/ipynb/__file_snapshots__/elife-50356.ipynb
- src/codecs/jats/__file_snapshots__/elife-30274-v1.yaml
- src/codecs/jats/__file_snapshots__/elife-43154-v2.yaml
- src/codecs/jats/__file_snapshots__/elife-46472-v3.yaml
- src/codecs/jats/__file_snapshots__/elife-46793-v1.yaml
- src/codecs/jats/__file_snapshots__/elife-52882-v2.yaml
- src/codecs/jats/__file_snapshots__/f1000-7-1655-v1.yaml
- src/codecs/jats/__file_snapshots__/f1000-8-1394-v1.yaml
- src/codecs/jats/__file_snapshots__/f1000-8-978-v1.yaml
- src/codecs/jats/__file_snapshots__/ijm-00202.yaml
- src/codecs/jats/index.ts
- src/codecs/md/__file_snapshots__/elife-50356.md
- src/codecs/xmd/__file_snapshots__/elife-50356.Rmd
Closes #816 and addresses part of #413 (to have `identifiers` for `references` in fixtures).
> HTML: Encode DOI & other identifiers into References section

- src/codecs/md/md.test.ts
- src/codecs/md/plugins/cite.ts
When transforming MD, Encoda would treat links containing email addresses (`[hello@stenci.la](mailto:hello@stenci.la)`) as Citations. This PR fixes the issue.
> fix(MD): Don't treat email addresses as citations

- src/codecs/jats/__file_snapshots__/elife-43154-v2.yaml
- src/codecs/jats/__file_snapshots__/elife-52882-v2.yaml
- src/codecs/jats/__file_snapshots__/plosone-0178565.yaml
- src/codecs/jats/index.ts
- src/codecs/plos/__file_snapshots__/pcbi-1007273.yaml
- src/codecs/plos/__file_snapshots__/pmed-1002858.yaml
- src/codecs/plos/__file_snapshots__/pone-0216012.yaml
> fix: Add equation id and alttext for MathML in JATS

- src/codecs/jats/index.ts
As can be seen in #876 tools like Pandoc or LaTeXML produce MathML nodes with different namespaces.
LaTeXML's `m:math` is currently not read by `encoda`.
A simple fix is to also look for this namespace in the JATS decoder. I looked into doing the right thing and trying to read the namespace but this is probably a good enough solution if you want to include this.
According to the JATS tag browser `m` is common even though `mml` seems to be the official standard.
> MathML Namespacing: The vast majority of users of this Tag Set use the DTDs as their primary (or only) model, so this Tag Set is maintained to ensure that users of DTDs and DTD-based tools will work well. Because DTDs do not “play well” with namespaces, and most DTD-based tools are not namespace aware, the MathML namespace has …
> fix: Allow MathML elements with `m:math` namespace in JATS

- src/codecs/jats/__file_snapshots__/f1000-8-1394-v1.yaml
- src/codecs/jats/index.ts
Here's a proposal to read ids from Paragraphs in JATS XML.
I've auto-updated the fixtures as well.
Turns
```xml
<body>
<p id="p1">Text<fn id="idm6"><p id="footnote1">Footy note.</p></fn></p>
</body>
```
into
```json
"content": [
{
"type": "Paragraph",
"id": "p1",
"content": [
"Text"
]
},
{
"type": "Paragraph",
"id": "footnote1",
"content": [
"Footy note."
]
}
]
```
(Adding support for footnotes <fn> would probably be a separate useful thing, but for me this would already help identifying footnotes and be useful in general i believe when reading JATS.)
> feat(JATS): Read ids of paragraphs

- src/codecs/jats/index.ts
This adds ids from JATS XML (if available) to graphic objects.
> feat(JATS): Decode ids from `graphic` objects

- src/codecs/jats/__file_snapshots__/fig.jats.xml
- src/codecs/jats/__file_snapshots__/fig.yaml
- src/codecs/jats/__fixtures__/fig.xml
- src/codecs/jats/index.ts
Here is an attempt at reading the permissions/license of a figure in JATS analogous to the main article license.
I'm not entirely sure how a figure with multiple images and diverging licenses should be handled:
> Contents of Permissions: The sub-elements of <permissions> are repeatable. If multiple values are applicable (such as multiple copyright years), they should be tagged separately rather than as multiple values within a single element. Repeated values do not describe the source of the material, they describe the current Intellectual Property for the article or object. 
https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/permissions.html
On https://jats4r.org/permissions there are examples with repeated `<permissions>` elements:
I would think however that it's better in such …
> feat(JATS): Read permissions element from figures

- src/codecs/jats/__file_snapshots__/elife-52882-v2.yaml
- src/codecs/jats/__fixtures__/equation.jats.xml
- src/codecs/jats/index.ts
This adds extracting the label field from a `disp-formula`.
https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/label.html
Example:
```xml
<disp-formula id="S0.Ex1">
<label>Special-Label</label>
<mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML" alttext="a=b" display="block">
<mml:mrow>
<mml:mi>a</mml:mi>
<mml:mo>=</mml:mo>
<mml:mi>b</mml:mi>
</mml:mrow>
</mml:math>
</disp-formula>
```
To 
```json
{
"type": "MathBlock",
"id": "S0.Ex9",
"label": "Special-Label",
"mathLanguage": "mathml",
"text": "<mml:math xmlns:mml=\"http://www.w3.org/1998/Math/MathML\" alttext=\"a=b\" display=\"block\"><mml:mrow><mml:mi>a</mml:mi><mml:mo>=</mml:mo><mml:mi>b</mml:mi></mml:mrow></mml:math>",
"meta": {
"altText": "a=b"
}
}
```
> feat(JATS): Add label field to MathBlocks
